ALTER TABLE notes
ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

ALTER TABLE notes
ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE notes
ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE notes
ALTER COLUMN updated_at SET DEFAULT NOW();
