/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type { EditorThemeClasses } from "lexical";

import "./AppEditorTheme.css";

const theme: EditorThemeClasses = {
  autocomplete: "AppEditor__autocomplete",
  blockCursor: "AppEditor__blockCursor",
  characterLimit: "AppEditor__characterLimit",
  code: "AppEditor__code",
  codeHighlight: {
    atrule: "AppEditor__tokenAttr",
    attr: "AppEditor__tokenAttr",
    boolean: "AppEditor__tokenProperty",
    builtin: "AppEditor__tokenSelector",
    cdata: "AppEditor__tokenComment",
    char: "AppEditor__tokenSelector",
    class: "AppEditor__tokenFunction",
    "class-name": "AppEditor__tokenFunction",
    comment: "AppEditor__tokenComment",
    constant: "AppEditor__tokenProperty",
    deleted: "AppEditor__tokenDeleted",
    doctype: "AppEditor__tokenComment",
    entity: "AppEditor__tokenOperator",
    function: "AppEditor__tokenFunction",
    important: "AppEditor__tokenVariable",
    inserted: "AppEditor__tokenInserted",
    keyword: "AppEditor__tokenAttr",
    namespace: "AppEditor__tokenVariable",
    number: "AppEditor__tokenProperty",
    operator: "AppEditor__tokenOperator",
    prolog: "AppEditor__tokenComment",
    property: "AppEditor__tokenProperty",
    punctuation: "AppEditor__tokenPunctuation",
    regex: "AppEditor__tokenVariable",
    selector: "AppEditor__tokenSelector",
    string: "AppEditor__tokenSelector",
    symbol: "AppEditor__tokenProperty",
    tag: "AppEditor__tokenProperty",
    unchanged: "AppEditor__tokenUnchanged",
    url: "AppEditor__tokenOperator",
    variable: "AppEditor__tokenVariable",
  },
  embedBlock: {
    base: "AppEditor__embedBlock",
    focus: "AppEditor__embedBlockFocus",
  },
  hashtag: "AppEditor__hashtag",
  heading: {
    h1: "AppEditor__h1",
    h2: "AppEditor__h2",
    h3: "AppEditor__h3",
    h4: "AppEditor__h4",
    h5: "AppEditor__h5",
    h6: "AppEditor__h6",
  },
  hr: "AppEditor__hr",
  hrSelected: "AppEditor__hrSelected",
  image: "editor-image",
  indent: "AppEditor__indent",
  inlineImage: "inline-editor-image",
  layoutContainer: "AppEditor__layoutContainer",
  layoutItem: "AppEditor__layoutItem",
  link: "AppEditor__link",
  list: {
    checklist: "AppEditor__checklist",
    listitem: "AppEditor__listItem",
    listitemChecked: "AppEditor__listItemChecked",
    listitemUnchecked: "AppEditor__listItemUnchecked",
    nested: {
      listitem: "AppEditor__nestedListItem",
    },
    olDepth: [
      "AppEditor__ol1",
      "AppEditor__ol2",
      "AppEditor__ol3",
      "AppEditor__ol4",
      "AppEditor__ol5",
    ],
    ul: "AppEditor__ul",
  },
  ltr: "AppEditor__ltr",
  mark: "AppEditor__mark",
  markOverlap: "AppEditor__markOverlap",
  paragraph: "AppEditor__paragraph",
  quote: "AppEditor__quote",
  rtl: "AppEditor__rtl",
  specialText: "AppEditor__specialText",
  tab: "AppEditor__tabNode",
  table: "AppEditor__table",
  tableAddColumns: "AppEditor__tableAddColumns",
  tableAddRows: "AppEditor__tableAddRows",
  tableAlignment: {
    center: "AppEditor__tableAlignmentCenter",
    right: "AppEditor__tableAlignmentRight",
  },
  tableCell: "AppEditor__tableCell",
  tableCellActionButton: "AppEditor__tableCellActionButton",
  tableCellActionButtonContainer: "AppEditor__tableCellActionButtonContainer",
  tableCellHeader: "AppEditor__tableCellHeader",
  tableCellResizer: "AppEditor__tableCellResizer",
  tableCellSelected: "AppEditor__tableCellSelected",
  tableFrozenColumn: "AppEditor__tableFrozenColumn",
  tableFrozenRow: "AppEditor__tableFrozenRow",
  tableRowStriping: "AppEditor__tableRowStriping",
  tableScrollableWrapper: "AppEditor__tableScrollableWrapper",
  tableSelected: "AppEditor__tableSelected",
  tableSelection: "AppEditor__tableSelection",
  text: {
    bold: "AppEditor__textBold",
    capitalize: "AppEditor__textCapitalize",
    code: "AppEditor__textCode",
    highlight: "AppEditor__textHighlight",
    italic: "AppEditor__textItalic",
    lowercase: "AppEditor__textLowercase",
    strikethrough: "AppEditor__textStrikethrough",
    subscript: "AppEditor__textSubscript",
    superscript: "AppEditor__textSuperscript",
    underline: "AppEditor__textUnderline",
    underlineStrikethrough: "AppEditor__textUnderlineStrikethrough",
    uppercase: "AppEditor__textUppercase",
  },
};

export default theme;
